name: example-environment
channels:
 - conda-forge
 - bioconda
dependencies:
 - bioconductor-myvariant
 - bedtools
 - future
 - requests
 - numpy==1.16
 - sphinx>=1.4
 - ipykernel
 - nbsphinx
 - pandas
 - pybedtools==0.8.0
 - python-docx
 - pip:
     - requests_cache
     - git+https://github.com/jrderuiter/pybiomart.git
